[workspace]
[package]
name = "log-crate"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = ["no_std"]
solana-program = ["solana-account-info","solana-entrypoint","solana-msg","solana-pubkey"]
solana-program-mono = ["dep:solana-program"]
no_std = ["pinocchio"]
provide-handlers = []

[dependencies]
pinocchio = { version = "0.8", git = "https://github.com/rustopian/pinocchio.git", branch = "rustopian/slot-hashes-sysvar", optional = true }
solana-account-info = { version = "2.2.1", default-features = false, optional = true }
solana-entrypoint = { package = "solana-program-entrypoint", version = "2.2.1", default-features = false, optional = true }
solana-msg = { version = "2.2.1", default-features = false, optional = true }
solana-pubkey = { version = "2.2.0", default-features = false, optional = true }
solana-program = { version = "2.2.0", default-features = false, optional = true }

[lib]
crate-type = ["cdylib", "lib"] 
