# eisodos_benchmarks.toml for log-crate

[[benchmark]]
id = "log_solana"
# Path to the function within this crate
function = "log_crate::solana_benches::run_log_bench"
entrypoints = ["solana-program"]
features = [
    { entrypoint = "solana-program", features = ["std"] }
]
# No specific input_data or account_setups needed for basic log test

[[benchmark]]
id = "log_pinocchio"
function = "log_crate::pinocchio_benches::run_log_bench"
entrypoints = ["pinocchio"]
features = [
    { entrypoint = "pinocchio", features = ["no_std"] } # Or simply [] if no_std is implicit or default
]
# No specific input_data or account_setups needed for basic log test 