# This Cargo.toml defines a temporary, self-contained workspace for a single benchmark run.
[workspace]
# The benchmarked crate will be copied here and listed as a member.
members = [ "%%BENCHED_CRATE_COPY_DIR_NAME%%" ]

# Workspace-level dependencies, like 'pinocchio', will be injected here by the script.
# This allows the copied benchmarked crate to resolve its 'workspace = true' dependencies.
%%WORKSPACE_DEPENDENCIES_BLOCK%%

# Definition for the benchmark runner package itself.
[package]
name = "eisodos-bench-%%BENCH_ID%%"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"] # Compile as a dynamic system library for SBF

[dependencies]
# Depend on pinocchio from the workspace defined above
pinocchio = { workspace = true }

# Dependency on the Pinocchio entrypoint harness/program itself.
# Explicitly disable default features to avoid pulling in std transitively.
eisodos-pinocchio = { path = "%%EISODOS_PINOCCHIO_PATH%%", default-features = false }

# Dependency on the benchmarked crate (which is now a workspace member).
# The placeholder %%CRATE_NAME%% refers to the original crate name.
%%CRATE_NAME%% = { path = "%%BENCHED_CRATE_COPY_DIR_NAME%%", features = [%%CRATE_FEATURES%%] }

[profile.release]
panic = "abort"
lto = "thin"
codegen-units = 1
strip = true
opt-level = 3 