# eisodos_benchmarks.toml for transfer-crate

[[benchmark]]
id = "transfer_solana"
function = "transfer_crate::solana_benches::run_transfer_bench"
entrypoints = ["solana-program"]
features = [
    { entrypoint = "solana-program", features = ["std"] }
]
# Using dotted keys for instruction_payload
instruction_payload.tag = 0
instruction_payload.amount = 1000000000
# Accounts: Source, Destination, SystemProgram (to be handled by executor setup)

[[benchmark]]
id = "transfer_pinocchio"
function = "transfer_crate::pinocchio_benches::run_transfer_bench"
entrypoints = ["pinocchio"]
features = [
    # Added provide-handlers for consistency with log-crate for no_std SBF builds
    { entrypoint = "pinocchio", features = ["no_std", "provide-handlers"] }
]
# Using dotted keys for instruction_payload
instruction_payload.tag = 0
instruction_payload.amount = 1000000000
# Accounts: Source, Destination (SystemProgram implicit for Pinocchio CPI) 