[package]
name = "ping-crate"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
# Pinocchio SDK is needed for ProgramResult and potentially other types
# Assuming it's available via the main workspace
pinocchio = { workspace = true }

[lib]
crate-type = ["rlib"] # Library crate for benchmarking 