[[benchmark]]
id = "ping_example_pinocchio"
function = "ping_crate::benchmarking::ping_for_benchmark"
entrypoints = ["pinocchio", "solana-program"]
features = [
    { entrypoint = "pinocchio", features = [] },
    { entrypoint = "solana-program", features = ["std"] }
]