# Autogenerated from run_eisodos_benchmarks.py to keep configuration data in a single place.
# This module should have **no** runtime side-effects so it can be freely imported.

# Two-step rewrite approach using solana-program breakout as canonical intermediate
NORMALIZE_TO_BREAKOUT = {
    # Convert FROM any format TO solana-program breakout crates
    
    # From pinocchio
    r"\bpinocchio::account_info::":     "solana_account_info::",
    r"\bpinocchio::pubkey::":           "solana_pubkey::",
    r"\bpinocchio::program_error::":    "solana_program_error::",
    r"\bpinocchio::log::":              "solana_msg::",
    r"\bpinocchio::":                   "solana_entrypoint::",
    
    # From monolithic solana_program - be specific, no catch-all
    r"\bsolana_program::account_info::": "solana_account_info::",
    r"\bsolana_program::pubkey::":       "solana_pubkey::",
    r"\bsolana_program::program_error::": "solana_program_error::",
    r"\bsolana_program::entrypoint::":   "solana_entrypoint::",
    r"\bsolana_program::entrypoint_deprecated::": "solana_entrypoint::",
    r"\bsolana_program::msg::":          "solana_msg::",
    r"\bsolana_program::instruction::":  "solana_instruction::",
    # For program::invoke and system functions, they should go to appropriate crates
    r"\bsolana_program::program::":      "solana_entrypoint::",  # invoke functions
    
    # Handle newer crates that don't exist in breakout world
    r"\bsolana_cpi::":                   "solana_entrypoint::",  # CPI functions -> entrypoint
    r"\bsolana_system_interface::instruction": "solana_system_instruction",  # system instruction functions
    r"\bsolana_system_interface::program": "solana_system_program",  # system program constants
}

DENORMALIZE_FROM_BREAKOUT = {
    # Convert FROM solana-program breakout TO target format
    
    "pinocchio": {
        r"\bsolana_account_info::":      "pinocchio::account_info::",
        r"\bsolana_pubkey::":            "pinocchio::pubkey::",
        r"\bsolana_program_error::":     "pinocchio::program_error::",
        r"\bsolana_entrypoint::":        "pinocchio::",
        r"\bsolana_msg::":               "pinocchio::log::",
        r"\bsolana_instruction::":       "pinocchio::instruction::",
    },
    
    "solana-program": {
        # Target is already breakout format - no transformation needed
    },
    
    "solana-program-mono": {
        r"\bsolana_account_info::":      "solana_program::account_info::",
        r"\bsolana_pubkey::":            "solana_program::pubkey::",
        r"\bsolana_program_error::":     "solana_program::program_error::",
        r"\bsolana_entrypoint::":        "solana_program::entrypoint::",
        r"\bsolana_msg::":               "solana_program::msg::",
        r"\bsolana_instruction::":       "solana_program::instruction::",
    },
    
    "solana-nostd-entrypoint": {
        # For nostd, we keep most breakout crates but change AccountInfo
        r"\bsolana_account_info::AccountInfo": "solana_nostd_entrypoint::NoStdAccountInfo",
        r"\bsolana_entrypoint::ProgramResult": "solana_program_error::ProgramResult",
        # solana_pubkey, solana_program_error, solana_msg stay as-is
    },
}

ENTRYPOINT_DEPS = {
    "pinocchio": """pinocchio = { workspace = true, default-features = false }""",

    "solana-program": """solana-account-info = { version = "^2.2", default-features = false }
solana-entrypoint = { package = "solana-program-entrypoint", version = "^2.2", default-features = false }
solana-program-error = { version = "^2.2", default-features = false }
solana-pubkey = { version = "^2.2", default-features = false }
solana-msg = { version = "^2.2", default-features = false }""",

    "solana-program-mono": """solana-program = { version = "^2.2", default-features = false }""",

    "solana-nostd-entrypoint": """solana-nostd-entrypoint = { version = "0.6", default-features = false }
solana-program-error = { version = "^2.2", default-features = false }
solana-pubkey = { version = "^2.2", default-features = false }""",
}

BENCHED_CRATE_DEPS = {
    "pinocchio": {
        "pinocchio": {
            "version": "0.8",
            "git": "https://github.com/rustopian/pinocchio.git",
            "branch": "rustopian/slot-hashes-sysvar",
            "default-features": False,
        }
    },
    "solana-program": {
        "solana-account-info": {
            "version": "^2.2",
            "default-features": False,
        },
        "solana-entrypoint": {
            "package": "solana-program-entrypoint",
            "version": "^2.2",
            "default-features": False,
        },
        "solana-program-error": {
            "version": "^2.2",
            "default-features": False,
        },
        "solana-pubkey": {
            "version": "^2.2",
            "default-features": False,
        },
        "solana-msg": {
            "version": "^2.2",
            "default-features": False,
        },
        "solana-instruction": {
            "version": "^2.2",
            "default-features": False,
        },
        "solana-cpi": {
            "version": "^2.2",
            "default-features": False,
        },
        "solana-system-interface": {
            "version": "^1.0",
            "default-features": False,
            "features": ["bincode"],
        },
    },
    "solana-program-mono": {
        "solana-program": {
            "version": "^2.2",
            "default-features": False,
        }
    },
    "solana-nostd-entrypoint": {
        "solana-nostd-entrypoint": {
            "version": "0.6",
            "default-features": False,
        },
        "solana-program-error": {
            "version": "^2.2",
            "default-features": False,
        },
        "solana-pubkey": {
            "version": "^2.2",
            "default-features": False,
        },
        "solana-msg": {
            "version": "^2.2",
            "default-features": False,
        },
        "solana-instruction": {
            "version": "^2.2",
            "default-features": False,
        },
        "solana-entrypoint": {
            "package": "solana-program-entrypoint",
            "version": "^2.2",
            "default-features": False,
        },
    },
}

# ---------------------------------------------------------------------------
# Identifier rewrite mappings used by scripts.rewriter
# ---------------------------------------------------------------------------
IDENTIFIER_MAPPINGS = {
    "pinocchio": {
        "ProgramResult": "pinocchio::ProgramResult",
        "AccountInfo": "pinocchio::account_info::AccountInfo",
        "Pubkey": "pinocchio::pubkey::Pubkey",
        "ProgramError": "pinocchio::program_error::ProgramError",
        "AccountMeta": "pinocchio::instruction::AccountMeta",
        "Instruction": "pinocchio::instruction::Instruction",
        "invoke": "pinocchio::program::invoke",
        "invoke_signed": "pinocchio::program::invoke_signed",
        "sol_log": "pinocchio::log::sol_log",
        "msg": "pinocchio::log::sol_log",
        "CpiAccount": "pinocchio::account_info::AccountInfo",
        "Account": "pinocchio::account_info::AccountInfo",
        "no_allocator": "pinocchio::no_allocator",
        "nostd_panic_handler": "pinocchio::nostd_panic_handler",
        "invoke_signed_unchecked": "pinocchio::program::invoke_signed_unchecked",
    },

    "solana-program": {
        "ProgramResult": "solana_entrypoint::ProgramResult",
        "AccountInfo": "solana_account_info::AccountInfo",
        "Pubkey": "solana_pubkey::Pubkey",
        "ProgramError": "solana_program_error::ProgramError",
        "AccountMeta": "solana_instruction::AccountMeta",
        "Instruction": "solana_instruction::Instruction",
        "invoke": "solana_cpi::invoke",
        "invoke_signed": "solana_cpi::invoke_signed",
        "sol_log": "solana_msg::sol_log",
        "msg": "solana_msg::msg",
        "next_account_info": "solana_account_info::next_account_info",
        "CpiAccount": "solana_account_info::AccountInfo",
        "Account": "solana_account_info::AccountInfo",
        "create_account": "solana_system_interface::instruction::create_account",
        "ID": "solana_system_interface::program::ID",
    },

    "solana-program-mono": {
        "ProgramResult": "solana_program::entrypoint::ProgramResult",
        "AccountInfo": "solana_program::account_info::AccountInfo",
        "Pubkey": "solana_program::pubkey::Pubkey",
        "ProgramError": "solana_program::program_error::ProgramError",
        "AccountMeta": "solana_program::instruction::AccountMeta",
        "Instruction": "solana_program::instruction::Instruction",
        "invoke": "solana_program::program::invoke",
        "invoke_signed": "solana_program::program::invoke_signed",
        "sol_log": "solana_program::log::sol_log",
        "msg": "solana_program::msg",
        "next_account_info": "solana_program::account_info::next_account_info",
        "CpiAccount": "solana_program::account_info::AccountInfo",
        "Account": "solana_program::account_info::AccountInfo",
        "create_account": "solana_program::system_instruction::create_account",
        "ID": "solana_program::system_program::ID",
    },

    "solana-nostd-entrypoint": {
        "ProgramResult": "solana_program_error::ProgramResult",
        "AccountInfo": "solana_nostd_entrypoint::NoStdAccountInfo",
        "Pubkey": "solana_pubkey::Pubkey",
        "ProgramError": "solana_program_error::ProgramError",
        "AccountMeta": "solana_instruction::AccountMeta",
        "Instruction": "solana_instruction::Instruction",
        "invoke": "solana_entrypoint::invoke",
        "invoke_signed": "solana_entrypoint::invoke_signed",
        "sol_log": "solana_msg::sol_log",
        "msg": "solana_msg::sol_log",
        "CpiAccount": "solana_nostd_entrypoint::NoStdAccountInfo",
        "Account": "solana_nostd_entrypoint::NoStdAccountInfo",
    },
} 