# Autogenerated from run_eisodos_benchmarks.py to keep configuration data in a single place.
# This module should have **no** runtime side-effects so it can be freely imported.

REWRITE_TABLE = {
    # BUILD TARGET  →  { pattern : replacement }
    "pinocchio": {
        # monolithic sdk
        r"\bsolana_program::":          "pinocchio::",
        # breakout crates
        r"\bsolana_account_info::":     "pinocchio::account_info::",
        r"\bsolana_pubkey::":           "pinocchio::pubkey::",
        r"\bsolana_program_error::":    "pinocchio::program_error::",
        r"\bsolana_entrypoint::":       "pinocchio::",
        r"\bsolana_msg::":              "pinocchio::log::",
        # Handle specific types that may need path changes
        r"\bProgramResult":             "ProgramResult",
        r"\bAccountInfo":               "AccountInfo",
        r"\bPubkey":                    "Pubkey",
    },
    "solana-program": {  # breakout → breakout, pinocchio → breakout
        r"\bpinocchio::account_info::": "solana_account_info::",
        r"\bpinocchio::pubkey::":       "solana_pubkey::",
        r"\bpinocchio::program_error::": "solana_program_error::",
        r"\bpinocchio::":               "solana_entrypoint::",
        r"\bpinocchio::log::":          "solana_msg::",
    },
    "solana-program-mono": {
        r"\bsolana_account_info::":     "solana_program::account_info::",
        r"\bsolana_pubkey::":           "solana_program::pubkey::",
        r"\bsolana_program_error::":    "solana_program::program_error::",
        r"\bsolana_entrypoint::":       "solana_program::entrypoint::",
        r"\bsolana_msg::":              "solana_program::msg::",
        r"\bpinocchio::account_info::": "solana_program::account_info::",
        r"\bpinocchio::pubkey::":       "solana_program::pubkey::",
        r"\bpinocchio::program_error::": "solana_program::program_error::",
        r"\bpinocchio::":               "solana_program::entrypoint::",
        r"\bpinocchio::log::":          "solana_program::msg::",
    },
    "solana-nostd-entrypoint": {
        r"\bsolana_account_info::AccountInfo": "solana_nostd_entrypoint::NoStdAccountInfo",
        r"\bpinocchio::account_info::AccountInfo": "solana_nostd_entrypoint::NoStdAccountInfo",
        r"\bsolana_pubkey::":           "solana_pubkey::",
        r"\bpinocchio::pubkey::":       "solana_pubkey::",
        r"\bsolana_program_error::":    "solana_program_error::",
        r"\bpinocchio::program_error::": "solana_program_error::",
        r"\bsolana_entrypoint::ProgramResult":     "solana_program_error::ProgramResult",
        r"\bpinocchio::ProgramResult":            "solana_program_error::ProgramResult",
    },
}

ENTRYPOINT_DEPS = {
    "pinocchio": """pinocchio = { workspace = true, default-features = false }""",

    "solana-program": """solana-account-info = { version = "^2.2", default-features = false }
solana-entrypoint = { package = "solana-program-entrypoint", version = "^2.2", default-features = false }
solana-program-error = { version = "^2.2", default-features = false }
solana-pubkey = { version = "^2.2", default-features = false }
solana-msg = { version = "^2.2", default-features = false }""",

    "solana-program-mono": """solana-program = { version = "^2.2", default-features = false }""",

    "solana-nostd-entrypoint": """solana-nostd-entrypoint = { version = "0.6", default-features = false }
solana-program-error = { version = "^2.2", default-features = false }
solana-pubkey = { version = "^2.2", default-features = false }""",
}

BENCHED_CRATE_DEPS = {
    "pinocchio": {
        "pinocchio": {
            "version": "0.8",
            "git": "https://github.com/rustopian/pinocchio.git",
            "branch": "rustopian/slot-hashes-sysvar",
            "default-features": False,
        }
    },
    "solana-program": {
        "solana-account-info": {
            "version": "^2.2",
            "default-features": False,
        },
        "solana-entrypoint": {
            "package": "solana-program-entrypoint",
            "version": "^2.2",
            "default-features": False,
        },
        "solana-program-error": {
            "version": "^2.2",
            "default-features": False,
        },
        "solana-pubkey": {
            "version": "^2.2",
            "default-features": False,
        },
        "solana-msg": {
            "version": "^2.2",
            "default-features": False,
        },
    },
    "solana-program-mono": {
        "solana-program": {
            "version": "^2.2",
            "default-features": False,
        }
    },
    "solana-nostd-entrypoint": {
        "solana-nostd-entrypoint": {
            "version": "0.6",
            "default-features": False,
        },
        "solana-program-error": {
            "version": "^2.2",
            "default-features": False,
        },
        "solana-pubkey": {
            "version": "^2.2",
            "default-features": False,
        },
        "solana-msg": {
            "version": "^2.2",
            "default-features": False,
        },
    },
} 