# eisodos_benchmarks.toml for create-account-crate

[[benchmark]]
id = "create_account_solana"
function = "create_account_crate::solana_benches::run_create_account_bench"
entrypoints = ["solana-program"]
features = [
    { entrypoint = "solana-program", features = ["std"] }
]
# Using dotted keys for instruction_payload
instruction_payload.tag = 0
instruction_payload.lamports = 500000000
instruction_payload.space = 10
# Accounts: Funder, NewAccount, SystemProgram (to be handled by executor setup)

[[benchmark]]
id = "create_account_pinocchio"
function = "create_account_crate::pinocchio_benches::run_create_account_bench"
entrypoints = ["pinocchio"]
features = [
    { entrypoint = "pinocchio", features = ["no_std", "provide-handlers"] } 
]
# Using dotted keys for instruction_payload
instruction_payload.tag = 0
instruction_payload.lamports = 500000000
instruction_payload.space = 10
# Accounts: Funder, NewAccount (SystemProgram implicit for Pinocchio CPI) 